### ISSUE TITLE
EditOrder crashes on update

### ISSUE THREAD

**Issue by rpdids** [Techman224/CostingApp#6]
When user changes the item fields, the app crashes when the update button is clicked on.

**Comment by LeclaireD** [comment]
Error thrown is:: Caused by: android.database.sqlite.SQLiteException: near "(": syntax error (code 1): , while compiling: UPDATE Costs SET (Store='store') WHERE (CostID='1')

the syntax is found at line 120 in ActualDatabase.java

**Comment by LeclaireD** [comment]
It no longer crashes on updating
